name : Check Linting and Code Quality

on:
    push:
        branches: [master,dev]
    pull_request:
        branches: [master,dev]

jobs:
    lint:
        name: Lint TS (Biome)
        runs-on: ubuntu-latest
        
        steps:
            - name: 📦 Checkout Repo
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
                
            - name: 📦 Setup Node + PNPM + Install Deps
              uses: ./.github/actions/setup-node-pnpm
            
            - name: Setup Biome
              if: github.event_name=='pull_request'
              uses: biomejs/setup-biome@v2
              with:
                version: latest

            - name: Run Biome
              run: pnpm dlx biome ci .